apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-to-image
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: aryakh22/video-to-image:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
